const WebDevelopmentFrameworks = [
  "Angular",
  "AngularJS",
  "React",
  "Vue.js",
  "Svelte",
  "Backbone.js",
  "Ember.js",
  "Next.js",
  "NestJS",
  "Strapi",
  "Hapi",
  "Feathers",
  "LoopBack",
  "Express.js",
  "Meteor.js",
  "Koa.js",
  "Sails.js",
  "Spring",
  "Django",
  "Flask",
  "Ruby on Rails",
  "ASP.NET",
  "Laravel",
  "Symfony",
  "Zend Framework",
  "CodeIgniter",
  "Yii",
  "Phalcon",
  "Slim",
  "Lumen",
  "CakePHP",
  "FuelPHP",
]

const MobileDevelopment = [
  "Swift",
  "Kotlin",
  "Objective-C",
  "Java",
  "React Native",
  "Flutter",
  "Xamarin",
  "Ionic",
  "Cordova",
  "PhoneGap",
  "Mobile Angular UI",
  "Sencha Touch",
  "Onsen UI",
]

const ProgrammingLanguages = [
  "JavaScript",
  "TypeScript",
  "Python",
  "Ruby",
  "PHP",
  "C#",
  "Scala",
  "Elixir",
  "Golang",
  "Rust",
  "Perl",
  "C++",
  "Dart",
  "R",
]

const DatabaseManagement = [
  "SQL",
  "NoSQL",
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "Oracle",
  "Firebase",
  "SQLite",
]

const DevOpsTools = [
  "Docker",
  "Kubernetes",
  "AWS",
  "Azure",
  "Google Cloud",
  "DevOps",
  "CI/CD",
  "Jenkins",
  "Travis CI",
  "Git",
  "SVN",
  "Mercurial",
  "Vagrant",
  "Ansible",
  "Chef",
  "Puppet",
]

const UserInterfaceDesign = [
  "HTML",
  "HTML5",
  "CSS",
  "CSS3",
  "Sass",
  "Less",
  "bem",
  "Styled Components",
  "Bootstrap",
  "Foundation",
  "Materialize",
  "Semantic UI",
  "Ant Design",
  "Figma",
  "Sketch",
  "Adobe XD",
  "Photoshop",
  "Illustrator",
  "UX",
  "UI",
  "Usability",
  "Accessibility",
]

const ProjectManagement = [
  "Agile",
  "Scrum",
  "Kanban",
  "JIRA",
  "Asana",
  "Trello",
  "Microsoft Project",
]

const SoftwareTesting = [
  "Testing",
  "JUnit",
  "Selenium",
  "TestNG",
  "Cypress",
  "Mocha",
  "Chai",
  "Jest",
  "Enzyme",
  "WebDriver",
  "Appium",
  "Quality Assurance",
  "Unit Testing",
  "Integration Testing",
  "Functional Testing",
  "System Testing",
  "Performance Testing",
  "Load Testing",
  "Stress Testing",
  "Mobile Testing",
]

const Analytics = [
  "Analytics",
  "Google Analytics",
  "google tag manager",
  "gtm",
  "bigquery",
  "big query",
  "redshift",
  "snowflake",
  "adobe analytics",
  "adobe launch",
  "adobe dtm",
  "adobe target",
  "adobe audience manager",
  "cdp",
  "dmp",
  "tealium",
  "Tableau",
  "Power BI",
  "looker",
  "Data Visualization",
  "D3.js",
  "Highcharts",
  "AmCharts",
  "one trust",
  "fivetran",
  "airbyte",
  "stitch",
  "singer",
  "dbt",
  "airflow",
  "databricks",
]

const DataScience = [
  "Data Analysis",
  "Big Data",
  "Hadoop",
  "Spark",
  "Data Science",
  "Machine Learning",
  "AI",
  "Artificial Intelligence",
  "TensorFlow",
  "PyTorch",
  "Keras",
  "Deep Learning",
  "Neural Networks",
  "Computer Vision",
  "NLP",
  "Natural Language Processing",
  "R",
  "MATLAB",
  "Julia",
]

const CloudComputing = [
  "AWS",
  "Azure",
  "Google Cloud",
  "IBM Cloud Functions",
  "Oracle Functions",
  "Alibaba Function Compute",
  "Cloudflare Workers",
  "AWS Lambda",
  "Google Functions",
  "Azure Functions",
  "heroku",
  "vercel",
]

const FrontendDevelopmentTools = [
  "Webpack",
  "Babel",
  "Grunt",
  "Gulp",
  "Redux",
  "MobX",
  "Flux",
  "GraphQL",
  "Apollo",
  "REST",
  "SOAP",
  "WebSockets",
  "WebRTC",
]

const SecurityAndCompliance = [
  "OAuth",
  "JWT",
  "OpenID",
  "SAML",
  "Security",
  "Cybersecurity",
  "Penetration Testing",
  "Ethical Hacking",
  "OAuth2",
  "LDAP",
  "Kerberos",
  "NTLM",
  "RADIUS",
  "Diameter",
]

const ServerAndInfrastructure = ["Nginx", "Apache", "Tomcat", "CRI-O", "Containerd", "Rkt", "LXC"]

const GameDevelopment = [
  "Unity",
  "Unreal Engine",
  "CryEngine",
  "GameMaker Studio",
  "Vulkan",
  "DirectX",
  "OpenGL",
  "WebGL",
  "Three.js",
  "Babylon.js",
]

const ScriptingAndAutomation = ["Shell scripting", "Python", "Ruby", "Perl", "Bash", "PowerShell"]

const MonitoringAndLogging = [
  "Prometheus",
  "Grafana",
  "Zabbix",
  "Nagios",
  "Datadog",
  "Splunk",
  "ELK Stack",
  "InfluxDB",
  "Graphite",
  "New Relic",
  "Log4j",
  "SLF4J",
  "Logback",
  "Zap",
  "Serilog",
  "NLog",
  "log4net",
  "Winston",
  "Bunyan",
  "Pino",
]
const RoboticsAndEmbeddedSystems = [
  "ROS (Robot Operating System)",
  "Gazebo",
  "Arduino",
  "Raspberry Pi",
  "BeagleBone",
  "ESP32",
  "ESP8266",
]

const MessageBrokersAndQueues = [
  "RabbitMQ",
  "Apache Kafka",
  "ActiveMQ",
  "ZeroMQ",
  "Pulsar",
  "RocketMQ",
  "NSQ",
  "Celery",
  "Kue",
  "Bull",
]

const SearchEngineOptimizationAndMarketing = [
  "SEO",
  "Search Engine Optimization",
  "PPC",
  "Pay Per Click",
  "Conversion Rate Optimization",
  "A/B Testing",
  "Multivariate Testing",
]

const ContentManagementSystems = [
  "WordPress",
  "Drupal",
  "Joomla",
  "Magento",
  "Shopify",
  "Adobe Experience Manager",
  "Typo3",
]

const EnterpriseSoftwareAndFrameworks = [
  "SAP",
  "Oracle Applications",
  "Microsoft Dynamics",
  "Salesforce",
  "NetSuite",
]

const VirtualAndAugmentedReality = [
  "VR",
  "Virtual Reality",
  "Augmented Reality",
  "Unity",
  "Unreal Engine",
]

const DataEngineeringAndWarehousing = [
  "ETL",
  "Data Warehousing",
  "Redshift",
  "BigQuery",
  "Snowflake",
  "Apache Nifi",
  "StreamSets",
]

const LegalAndRegulatoryCompliance = [
  "GDPR Compliance",
  "HIPAA Compliance",
  "SOX Compliance",
  "Data Privacy Laws",
]

const BlockchainAndDistributedTechnologies = [
  "Blockchain",
  "Ethereum",
  "Smart Contracts",
  "Crypto",
  "Cryptography",
  "Hyperledger Fabric",
  "R3 Corda",
  "Quorum",
]

const Languages = ["english", "spanish", "french", "german"]

const AdobeTools = ["adobe experience manager", "aem", "osgi", "htl", "magento"]

const hardSkills = [
  ...WebDevelopmentFrameworks,
  ...MobileDevelopment,
  ...ProgrammingLanguages,
  ...DatabaseManagement,
  ...DevOpsTools,
  ...UserInterfaceDesign,
  ...ProjectManagement,
  ...SoftwareTesting,
  ...Analytics,
  ...DataScience,
  ...CloudComputing,
  ...FrontendDevelopmentTools,
  ...SecurityAndCompliance,
  ...ServerAndInfrastructure,
  ...GameDevelopment,
  ...ScriptingAndAutomation,
  ...MonitoringAndLogging,
  ...RoboticsAndEmbeddedSystems,
  ...MessageBrokersAndQueues,
  ...SearchEngineOptimizationAndMarketing,
  ...ContentManagementSystems,
  ...EnterpriseSoftwareAndFrameworks,
  ...VirtualAndAugmentedReality,
  ...DataEngineeringAndWarehousing,
  ...LegalAndRegulatoryCompliance,
  ...BlockchainAndDistributedTechnologies,
  ...Languages,
  ...AdobeTools,
]

export default hardSkills
